/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0.1-40-gabb609bb58"
#endif /* AVUTIL_FFVERSION_H */
